version: "3.9"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
    default:
      driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${uid}:${gid}
    network_mode: 'host'
    volumes:
      - /NAS/srvdata/jellyfin/config:/config
      - /NAS/srvdata/jellyfin/cache:/cache
      - /NAS:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
#    environment:
#      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  shoko_server:
    container_name: shokoserver
    image: shokoanime/server:daily-amd64
    restart: always
    environment:
      - "PUID=${uid}"
      - "PGID=${gid}"
      - "TZ=${TZ}"
    ports:
      - "8111:8111"
    volumes:
      - "/NAS/srvdata/shoko:/home/shoko/.shoko"
      - "/NAS/Anime:/mnt/anime"
      - "/NAS/Hentai:/mnt//hentai"
      - "/NAS/ShokoImport:/mnt/import"

  metatube:
    container_name: metatube
    image: metatube/metatube-server:latest
    ports:
      - "8081:8080"
    restart: unless-stopped

  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    volumes:
      - /NAS/Manga:/manga
      - /NAS/srvdata/kavita:/kavita/config
    environment:
      - TZ=${TZ}
    ports:
      - "5000:5000"
    restart: unless-stopped
